apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${nginx_namespace}
resources:
  - repository.yaml
  - release.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - values.yaml=config.yaml
generatorOptions:
  disableNameSuffixHash: true