apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: ${nginx_namespace}
spec:
  targetNamespace: ${nginx_namespace}
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: ${nginx_chart_version}
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: ${nginx_namespace}
  interval: 1m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: nginx-config
      