apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  targetNamespace: nginx
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: ${nginx_chart_version}
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: nginx
  interval: 1m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    controller:
      replicaCount: 2
      service:
        annotations: 
          "service.beta.kubernetes.io/azure-load-balancer-internal" : "true"
          "service.beta.kubernetes.io/port_80_no_probe_rule" : "true"
          "service.beta.kubernetes.io/port_443_no_probe_rule" : "true"
          "xlscsde.nhs.uk/dns-record" : "nginx"

      admissionWebhooks:
        enabled: true
        timeoutSeconds: 30