name: Create Release Branch from Main

on:
  push:
    branches:
    - 'main'

jobs:
  semver:
    uses: lsc-sde/lsc-sde/.github/workflows/semver.yaml@main
    with:
      useConfigFile: true

  # Creates a release branch based on symver and pushes it
  flux:
    uses: lsc-sde/lsc-sde/.github/workflows/flux.yaml@main
    needs: semver
    with:
      symver: ${{ needs.semver.outputs.GitVersion_SemVer }}

  